# Generated by Django 4.1.1 on 2022-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Original",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("place_name", models.TextField()),
                ("address_name", models.TextField()),
                ("road_address_name", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("category_group_name", models.CharField(max_length=20)),
                ("category_name", models.TextField(null=True)),
                ("place_url", models.URLField()),
                ("create_dt", models.DateTimeField(auto_now_add=True)),
                ("update_dt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
