# Generated by Django 4.1.1 on 2022-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Original",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("place_area", models.CharField(max_length=10)),
                ("place_name", models.TextField(verbose_name="상호명")),
                ("address_name", models.TextField(verbose_name="지번 주소")),
                ("road_address_name", models.TextField(verbose_name="도로명 주소")),
                ("phone", models.CharField(max_length=20, verbose_name="전화번호")),
                ("category_group_name", models.CharField(max_length=20)),
                ("category_name", models.TextField(blank=True)),
                ("place_url", models.URLField(verbose_name="위치정보 URL")),
                ("is_public", models.BooleanField(default=False, verbose_name="공개여부")),
                ("create_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="최종 수정 날짜"),
                ),
            ],
            options={
                "verbose_name": "카페 정보",
                "verbose_name_plural": "카페 목록",
                "managed": True,
            },
        ),
    ]
